version: '2'
services:
  server:
    build: .
    volumes:
       - /ms/miskillstech.com/code/runenv-config/ms/nginxproxy/var-www-html:/var/www/html
       - /ms/miskillstech.com/code/runenv-config/ms/nginxproxy/etc-supervisor-conf.d-services.conf:/etc/supervisor/conf.d/services.conf
       - /ms/miskillstech.com/code/runenv-config/ms/nginxproxy/etc-nginx-sites-enabled-default:/etc/nginx/sites-enabled/default
       - /ms/miskillstech.com/code/runenv-config/ms/nginxproxy/etc-nginx-snippets-fastcgi-php.conf:/etc/nginx/snippets/fastcgi-php.conf

    networks:
        - emr
    restart: unless-stopped

networks:
  emr:
    external:
      name: emr_default